"""add program catalog schema (phase 2.1)

Revision ID: 17004db94c98
Revises: 898842b69b84
Create Date: 2026-07-20 02:02:13.965528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17004db94c98'
down_revision: Union[str, Sequence[str], None] = '898842b69b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('MASTERS', 'DOCTORAL', 'CERTIFICATE', 'OTHER', name='degree_level'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('evidence_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unitid', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('ACADEMIC_CATALOG', 'DEPARTMENT_PAGE', 'GRADUATE_SCHOOL_PAGE', 'INTERNATIONAL_OFFICE', 'INSTITUTIONAL_REPORT', 'RANKING_PUBLISHER', name='source_type'), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unitid'], ['universities.unitid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unitid', 'base_url', name='uq_evidence_source_unitid_url')
    )
    op.create_index(op.f('ix_evidence_sources_unitid'), 'evidence_sources', ['unitid'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('fetch_method', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_source_id'], ['evidence_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_evidence_source_id'), 'source_snapshots', ['evidence_source_id'], unique=False)
    op.create_table('academic_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unitid', sa.Integer(), nullable=False),
    sa.Column('parent_unit_id', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.Enum('COLLEGE', 'SCHOOL', 'DEPARTMENT', 'DIVISION', 'INSTITUTE', 'OTHER', name='unit_type'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISCONTINUED', 'UNVERIFIED', name='entity_status'), nullable=False),
    sa.Column('last_seen_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('RAW', 'PARSED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'DOCUMENT_VERIFIED', 'REJECTED_AS_INVALID', name='verification_status'), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['academic_units.id'], ),
    sa.ForeignKeyConstraint(['unitid'], ['universities.unitid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_units_name'), 'academic_units', ['name'], unique=False)
    op.create_index(op.f('ix_academic_units_parent_unit_id'), 'academic_units', ['parent_unit_id'], unique=False)
    op.create_index(op.f('ix_academic_units_unitid'), 'academic_units', ['unitid'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_unit_id', sa.Integer(), nullable=False),
    sa.Column('degree_type_code', sa.String(length=20), nullable=False),
    sa.Column('raw_degree_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('cip_code', sa.String(length=20), nullable=True),
    sa.Column('program_url', sa.Text(), nullable=True),
    sa.Column('stem_designated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISCONTINUED', 'UNVERIFIED', name='entity_status'), nullable=False),
    sa.Column('last_seen_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('RAW', 'PARSED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'DOCUMENT_VERIFIED', 'REJECTED_AS_INVALID', name='verification_status'), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_units.id'], ),
    sa.ForeignKeyConstraint(['degree_type_code'], ['degree_types.code'], ),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_unit_id', 'degree_type_code', 'canonical_name', name='uq_program_identity')
    )
    op.create_index(op.f('ix_programs_academic_unit_id'), 'programs', ['academic_unit_id'], unique=False)
    op.create_index(op.f('ix_programs_canonical_name'), 'programs', ['canonical_name'], unique=False)
    op.create_table('program_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=False),
    sa.Column('alias_type', sa.Enum('CATALOG_ALIAS', 'FORMER_NAME', 'COMMON_ABBREVIATION', 'OTHER', name='program_alias_type'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'alias', name='uq_program_alias')
    )
    op.create_index(op.f('ix_program_aliases_alias'), 'program_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_program_aliases_program_id'), 'program_aliases', ['program_id'], unique=False)
    op.create_table('program_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(length=255), nullable=False),
    sa.Column('track_type', sa.Enum('THESIS', 'NON_THESIS', 'PROJECT', 'COURSEWORK', 'UNSPECIFIED', name='track_type'), nullable=False),
    sa.Column('modality', sa.Enum('IN_PERSON', 'ONLINE', 'HYBRID', 'UNSPECIFIED', name='modality'), nullable=False),
    sa.Column('campus_name', sa.String(length=255), nullable=True),
    sa.Column('credits_required', sa.Integer(), nullable=True),
    sa.Column('expected_duration_months', sa.Integer(), nullable=True),
    sa.Column('min_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('min_gpa_raw', sa.String(length=255), nullable=True),
    sa.Column('toefl_min', sa.Integer(), nullable=True),
    sa.Column('ielts_min', sa.Integer(), nullable=True),
    sa.Column('gre_policy', sa.Enum('REQUIRED', 'OPTIONAL', 'WAIVED', 'NOT_ACCEPTED', 'UNSPECIFIED', name='gre_policy'), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=True),
    sa.Column('international_share', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISCONTINUED', 'UNVERIFIED', name='entity_status'), nullable=False),
    sa.Column('last_seen_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('RAW', 'PARSED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'DOCUMENT_VERIFIED', 'REJECTED_AS_INVALID', name='verification_status'), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_tracks_program_id'), 'program_tracks', ['program_id'], unique=False)
    op.create_table('admission_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_track_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.Enum('GPA', 'TEST_SCORE', 'PREREQUISITE_COURSE', 'RECOMMENDATION_LETTERS', 'DOCUMENT', 'OTHER', name='requirement_type'), nullable=False),
    sa.Column('structured_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('last_seen_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('RAW', 'PARSED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'DOCUMENT_VERIFIED', 'REJECTED_AS_INVALID', name='verification_status'), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_track_id'], ['program_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_requirements_program_track_id'), 'admission_requirements', ['program_track_id'], unique=False)
    op.create_table('program_concentrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_track_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('last_seen_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('RAW', 'PARSED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'DOCUMENT_VERIFIED', 'REJECTED_AS_INVALID', name='verification_status'), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['program_track_id'], ['program_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_concentrations_program_id'), 'program_concentrations', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_concentrations_program_track_id'), 'program_concentrations', ['program_track_id'], unique=False)
    op.create_table('program_track_deadlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_track_id', sa.Integer(), nullable=False),
    sa.Column('intake_term', sa.String(length=50), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('priority_funding_deadline', sa.Date(), nullable=True),
    sa.Column('is_rolling', sa.Boolean(), nullable=False),
    sa.Column('deadline_raw_text', sa.Text(), nullable=False),
    sa.Column('last_seen_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('RAW', 'PARSED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'DOCUMENT_VERIFIED', 'REJECTED_AS_INVALID', name='verification_status'), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_track_id'], ['program_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_track_id', 'intake_term', name='uq_track_deadline_intake_term')
    )
    op.create_index(op.f('ix_program_track_deadlines_program_track_id'), 'program_track_deadlines', ['program_track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_track_deadlines_program_track_id'), table_name='program_track_deadlines')
    op.drop_table('program_track_deadlines')
    op.drop_index(op.f('ix_program_concentrations_program_track_id'), table_name='program_concentrations')
    op.drop_index(op.f('ix_program_concentrations_program_id'), table_name='program_concentrations')
    op.drop_table('program_concentrations')
    op.drop_index(op.f('ix_admission_requirements_program_track_id'), table_name='admission_requirements')
    op.drop_table('admission_requirements')
    op.drop_index(op.f('ix_program_tracks_program_id'), table_name='program_tracks')
    op.drop_table('program_tracks')
    op.drop_index(op.f('ix_program_aliases_program_id'), table_name='program_aliases')
    op.drop_index(op.f('ix_program_aliases_alias'), table_name='program_aliases')
    op.drop_table('program_aliases')
    op.drop_index(op.f('ix_programs_canonical_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_academic_unit_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_academic_units_unitid'), table_name='academic_units')
    op.drop_index(op.f('ix_academic_units_parent_unit_id'), table_name='academic_units')
    op.drop_index(op.f('ix_academic_units_name'), table_name='academic_units')
    op.drop_table('academic_units')
    op.drop_index(op.f('ix_source_snapshots_evidence_source_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_evidence_sources_unitid'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_table('degree_types')
    # ### end Alembic commands ###

    # Native Postgres ENUM types are not dropped by drop_table; without
    # this, a downgrade-then-upgrade cycle fails with "type already
    # exists" (same issue as migration 757e5ed4e214).
    for enum_name in (
        "requirement_type",
        "gre_policy",
        "modality",
        "track_type",
        "program_alias_type",
        "unit_type",
        "verification_status",
        "entity_status",
        "source_type",
        "degree_level",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
