"""add review pipeline schema (phase 2.2a)

Revision ID: 70f0fd69a8a3
Revises: 17004db94c98
Create Date: 2026-07-21 00:58:56.567471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70f0fd69a8a3'
down_revision: Union[str, Sequence[str], None] = '17004db94c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_review_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Enum('ACADEMIC_UNIT', 'PROGRAM', 'PROGRAM_TRACK', 'PROGRAM_TRACK_DEADLINE', 'PROGRAM_CONCENTRATION', 'ADMISSION_REQUIREMENT', name='catalog_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Enum('LOW_CONFIDENCE', 'FIRST_SEEN', 'CONFLICTS_WITH_EXISTING', 'ADAPTER_FALLBACK_USED', 'POSSIBLE_DUPLICATE', 'REPORTED_BY_USER', name='review_reason'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED', name='review_task_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_review_tasks_entity', 'data_review_tasks', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_data_review_tasks_status'), 'data_review_tasks', ['status'], unique=False)
    op.create_table('data_conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Enum('ACADEMIC_UNIT', 'PROGRAM', 'PROGRAM_TRACK', 'PROGRAM_TRACK_DEADLINE', 'PROGRAM_CONCENTRATION', 'ADMISSION_REQUIREMENT', name='catalog_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('current_verification_status', postgresql.ENUM('RAW', 'PARSED', 'NEEDS_REVIEW', 'USER_CONFIRMED', 'DOCUMENT_VERIFIED', 'REJECTED_AS_INVALID', name='verification_status', create_type=False), nullable=False),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('proposed_source_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED_KEPT_CURRENT', 'RESOLVED_TOOK_PROPOSED', name='conflict_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposed_source_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_conflicts_entity', 'data_conflicts', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_data_conflicts_status'), 'data_conflicts', ['status'], unique=False)
    op.create_table('parsed_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_documents_source_snapshot_id'), 'parsed_documents', ['source_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_documents_source_snapshot_id'), table_name='parsed_documents')
    op.drop_table('parsed_documents')
    op.drop_index(op.f('ix_data_conflicts_status'), table_name='data_conflicts')
    op.drop_index('ix_data_conflicts_entity', table_name='data_conflicts')
    op.drop_table('data_conflicts')
    op.drop_index(op.f('ix_data_review_tasks_status'), table_name='data_review_tasks')
    op.drop_index('ix_data_review_tasks_entity', table_name='data_review_tasks')
    op.drop_table('data_review_tasks')
    # ### end Alembic commands ###

    # Native Postgres ENUM types are not dropped by drop_table; without
    # this, a downgrade-then-upgrade cycle fails with "type already
    # exists" (same issue as migrations 757e5ed4e214 and 17004db94c98).
    # NOTE: 'verification_status' is deliberately NOT dropped here — it
    # was created by migration 757e5ed4e214 and is still used by tables
    # from that migration and 17004db94c98; only the enum types first
    # introduced in *this* migration are dropped.
    for enum_name in (
        "conflict_status",
        "review_task_status",
        "review_reason",
        "catalog_entity_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
