"""create universities and university_aliases

Revision ID: 757e5ed4e214
Revises: 
Create Date: 2026-07-18 16:04:07.874764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757e5ed4e214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('unitid', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sector', sa.Enum('PUBLIC', 'PRIVATE_NONPROFIT', 'PRIVATE_FOR_PROFIT', 'UNKNOWN', name='sector'), nullable=False),
    sa.Column('highest_degree_level', sa.Integer(), nullable=True),
    sa.Column('highest_degree_label', sa.String(length=100), nullable=True),
    sa.Column('masters_granting', sa.Boolean(), nullable=False),
    sa.Column('masters_granting_basis', sa.String(length=255), nullable=True),
    sa.Column('degree_granting', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('total_enrollment', sa.Integer(), nullable=True),
    sa.Column('graduate_enrollment', sa.Integer(), nullable=True),
    sa.Column('international_graduate_enrollment', sa.Integer(), nullable=True),
    sa.Column('enrollment_year', sa.Integer(), nullable=True),
    sa.Column('coverage_tier', sa.Enum('INDEXED', 'PROGRAMS_DISCOVERED', 'PROGRAMS_VERIFIED', 'ADMISSION_ENRICHED', 'FUNDING_ENRICHED', 'OUTCOME_ENRICHED', name='coverage_tier'), nullable=False),
    sa.Column('ipeds_year', sa.Integer(), nullable=False),
    sa.Column('source_dataset', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('unitid')
    )
    op.create_index(op.f('ix_universities_canonical_name'), 'universities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_universities_state'), 'universities', ['state'], unique=False)
    op.create_table('university_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unitid', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=False),
    sa.Column('alias_type', sa.Enum('IPEDS_ALIAS', 'FORMER_NAME', 'COMMON_ABBREVIATION', 'OTHER', name='alias_type'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unitid'], ['universities.unitid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unitid', 'alias', name='uq_university_alias')
    )
    op.create_index(op.f('ix_university_aliases_alias'), 'university_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_university_aliases_unitid'), 'university_aliases', ['unitid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_university_aliases_unitid'), table_name='university_aliases')
    op.drop_index(op.f('ix_university_aliases_alias'), table_name='university_aliases')
    op.drop_table('university_aliases')
    op.drop_index(op.f('ix_universities_state'), table_name='universities')
    op.drop_index(op.f('ix_universities_canonical_name'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
    # Native Postgres ENUM types are not dropped by drop_table; without this,
    # a downgrade-then-upgrade cycle fails with "type already exists".
    sa.Enum(name='coverage_tier').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sector').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='alias_type').drop(op.get_bind(), checkfirst=True)
