"""add cost, funding, and visa eligibility schema (phase 2.2c)

Revision ID: 86d9628e736e
Revises: 70f0fd69a8a3
Create Date: 2026-09-08 19:49:00.929082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '86d9628e736e'
down_revision: Union[str, Sequence[str], None] = '70f0fd69a8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Native Postgres ENUM types aren't auto-created by op.add_column the
    # way they are by op.create_table (which visits+creates types as part
    # of the CREATE TABLE DDL) — unlike the Phase 2.1 migration, every
    # column here is added to an *existing* table, so each new type needs
    # an explicit, one-time CREATE TYPE before anything references it.
    postgresql.ENUM(
        'DEGREE', 'CERTIFICATE', 'NON_CREDIT_CERTIFICATE', 'EXECUTIVE_EDUCATION',
        'MICROCREDENTIAL', 'UNKNOWN', name='credential_status',
    ).create(op.get_bind(), checkfirst=True)
    postgresql.ENUM(
        'I20_ELIGIBLE', 'NO_I20_ONLINE_ONLY', 'NO_I20_NON_DEGREE',
        'I20_DEPENDS_ON_CAMPUS_OR_TRACK', 'I20_ELIGIBILITY_UNCLEAR', 'NOT_APPLICABLE',
        name='visa_support_status',
    ).create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_tracks', sa.Column('estimated_annual_cost_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('program_tracks', sa.Column('estimated_annual_cost_raw', sa.Text(), nullable=True))
    op.add_column('program_tracks', sa.Column('visa_support_status_override', postgresql.ENUM('I20_ELIGIBLE', 'NO_I20_ONLINE_ONLY', 'NO_I20_NON_DEGREE', 'I20_DEPENDS_ON_CAMPUS_OR_TRACK', 'I20_ELIGIBILITY_UNCLEAR', 'NOT_APPLICABLE', name='visa_support_status', create_type=False), nullable=True))
    op.add_column('program_tracks', sa.Column('visa_support_status_override_raw_text', sa.Text(), nullable=True))
    op.add_column('programs', sa.Column('credential_status', postgresql.ENUM('DEGREE', 'CERTIFICATE', 'NON_CREDIT_CERTIFICATE', 'EXECUTIVE_EDUCATION', 'MICROCREDENTIAL', 'UNKNOWN', name='credential_status', create_type=False), nullable=False, server_default='UNKNOWN'))
    op.add_column('programs', sa.Column('visa_support_status', postgresql.ENUM('I20_ELIGIBLE', 'NO_I20_ONLINE_ONLY', 'NO_I20_NON_DEGREE', 'I20_DEPENDS_ON_CAMPUS_OR_TRACK', 'I20_ELIGIBILITY_UNCLEAR', 'NOT_APPLICABLE', name='visa_support_status', create_type=False), nullable=False, server_default='I20_ELIGIBILITY_UNCLEAR'))
    op.add_column('programs', sa.Column('visa_support_status_raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # requirement_type is an existing enum (created in 17004db94c98); add
    # the new FUNDING member for funding/assistantship admission_requirement
    # rows (§14 decision 8 — reuses this table rather than a new one). Must
    # run outside the same transaction that uses the new value, which is
    # already true here (upgrade() never inserts rows).
    op.execute("ALTER TYPE requirement_type ADD VALUE IF NOT EXISTS 'FUNDING'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'visa_support_status_raw_text')
    op.drop_column('programs', 'visa_support_status')
    op.drop_column('programs', 'credential_status')
    op.drop_column('program_tracks', 'visa_support_status_override_raw_text')
    op.drop_column('program_tracks', 'visa_support_status_override')
    op.drop_column('program_tracks', 'estimated_annual_cost_raw')
    op.drop_column('program_tracks', 'estimated_annual_cost_usd')
    # ### end Alembic commands ###

    # Postgres can't remove a single enum value without recreating the
    # type (and re-pointing every column/table that uses it); 'FUNDING'
    # is deliberately left in requirement_type on downgrade, same
    # tolerance as the undroppped-shared-enum-type note in
    # 70f0fd69a8a3 (verification_status). An unused enum member is
    # harmless; a value present in existing rows would make removal
    # actively wrong to attempt automatically anyway.

    # Both enum types are new in this migration and used only by the
    # columns just dropped above, so it's safe to drop them here — same
    # pattern as 70f0fd69a8a3's downgrade for its own new enum types.
    for enum_name in ("visa_support_status", "credential_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
