"""add carnegie classification and campus setting

Revision ID: 898842b69b84
Revises: 757e5ed4e214
Create Date: 2026-07-19 14:43:56.089325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898842b69b84'
down_revision: Union[str, Sequence[str], None] = '757e5ed4e214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('carnegie_classification', sa.Integer(), nullable=True))
    op.add_column('universities', sa.Column('carnegie_classification_label', sa.String(length=100), nullable=True))
    op.add_column('universities', sa.Column('campus_setting', sa.Integer(), nullable=True))
    op.add_column('universities', sa.Column('campus_setting_label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'campus_setting_label')
    op.drop_column('universities', 'campus_setting')
    op.drop_column('universities', 'carnegie_classification_label')
    op.drop_column('universities', 'carnegie_classification')
    # ### end Alembic commands ###
